[tool.poetry]
name = "pytrade-oanda"
packages = [{include = "oanda_client"}]
version = "0.1.0"
description = "Oanda brokerage adapter for pytrade"
authors = ["Kyle Widmann <Kyle.Widmann@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytrade = ">=0.1.0"
v20 = {git = "https://github.com/kylewidmann/v20-python", rev = "v1.0.0"}
pyyaml = "^6.0"
types-pyyaml = "^6.0.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
